# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, next]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    name: coverage for node@lts, redis@7
    env:
      node-version: lts/*
      redis-version: 7

    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Use Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ env.redis-version }}
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn build
      - run: yarn coverage
      - name: Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: yarn coveralls

  compatibility:
    runs-on: ubuntu-latest

    name: testing node@${{ matrix.node-version }}, redis@${{ matrix.redis-version }}

    strategy:
      matrix:
        node-version: [lts/*, lts/-1, current]
        redis-version: [7]
        include:
          - node-version: 'lts/*'
            redis-version: 5
          - node-version: 'lts/*'
            redis-version: 6

    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: yarn install --ignore-engines --frozen-lockfile --non-interactive
      - run: yarn build
      - run: yarn test
